"""Webhook Pipeline orchestrator — sequential stage execution.

Implements the ``WebhookPipeline`` class that runs incoming webhook
payloads through a strict dedup → loop_guard → dispatcher order.
Each stage can either PASS (continue to next) or DROP (stop processing).
Every stage result is written to the audit log.

Also exposes a FastAPI router with ``POST /webhooks/jira`` that feeds
into the pipeline.
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Protocol, runtime_checkable

import structlog
from fastapi import APIRouter, Request, status
from fastapi.responses import JSONResponse

__all__ = [
    "WebhookPayload",
    "StageAction",
    "StageResult",
    "PipelineResult",
    "PipelineStage",
    "WebhookPipeline",
    "DedupStage",
    "LoopGuardStage",
    "DispatcherStage",
    "build_webhook_pipeline",
    "router",
]

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

_logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------


class StageAction(str, Enum):
    """Possible actions a pipeline stage can return."""

    PASS = "pass"
    DROP = "drop"
    SIGNALED = "signaled"
    WORKFLOW_STARTED = "workflow_started"
    ITERATION_STARTED = "iteration_started"
    BUDGET_EXCEEDED = "budget_exceeded"
    BUDGET_CONFIGURATION_ERROR = "budget_configuration_error"
    APPROVAL_FORWARDED = "approval_forwarded"


@dataclass(frozen=True)
class WebhookPayload:
    """Normalized representation of an incoming webhook event.

    Attributes
    ----------
    event_id : str | None
        The ``X-Atlassian-Webhook-Identifier`` header value, or a
        derived hash from event+timestamp+issue_id.
    event_type : str
        The Jira webhook event type (e.g. ``jira:issue_updated``).
    issue_key : str
        The Jira issue key (e.g. ``PROJ-123``).
    actor_account_id : str | None
        The account ID of the user who triggered the event.
    assignee_account_id : str | None
        The account ID of the issue assignee.
    reporter_account_id : str | None
        The account ID of the issue reporter. Used for iteration
        authorization.
    comment_body : str | None
        The comment text (for ``comment_created`` events).
    trace_id : str | None
        Optional trace ID for correlation across services.
    raw_payload : dict[str, Any]
        The original raw webhook payload dict.
    headers : dict[str, str]
        Relevant HTTP headers from the incoming request.
    received_at : datetime
        Timestamp when the webhook was received.
    """

    event_id: str | None
    event_type: str
    issue_key: str
    actor_account_id: str | None = None
    assignee_account_id: str | None = None
    reporter_account_id: str | None = None
    comment_body: str | None = None
    trace_id: str | None = None
    raw_payload: dict[str, Any] = field(default_factory=dict)
    headers: dict[str, str] = field(default_factory=dict)
    received_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


@dataclass(frozen=True)
class StageResult:
    """Result returned by a single pipeline stage.

    Attributes
    ----------
    action : StageAction
        Whether the stage passed, dropped, or triggered a specific action.
    reason : str | None
        Human-readable reason for the action (especially for drops).
    trace_id : str | None
        Trace ID propagated or generated by the stage.
    metadata : dict[str, Any]
        Additional metadata from the stage (e.g. workflow_id, dept_id).
    """

    action: StageAction
    reason: str | None = None
    trace_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class PipelineResult:
    """Final result of the full pipeline execution.

    Attributes
    ----------
    final_action : StageAction
        The action from the last executed stage.
    stage_results : list[tuple[str, StageResult]]
        Ordered list of (stage_name, result) pairs for all executed stages.
    dropped_at : str | None
        Name of the stage that dropped the payload, or None if passed all.
    trace_id : str | None
        The trace ID associated with this pipeline run.
    """

    final_action: StageAction
    stage_results: list[tuple[str, StageResult]] = field(default_factory=list)
    dropped_at: str | None = None
    trace_id: str | None = None


# ---------------------------------------------------------------------------
# Stage Protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class PipelineStage(Protocol):
    """Protocol that all pipeline stages must implement."""

    @property
    def name(self) -> str:
        """Human-readable name of this stage."""
        ...

    async def check(self, payload: WebhookPayload) -> StageResult:
        """Process the payload and return a stage result.

        Returns StageAction.PASS to continue to the next stage,
        or any other action to stop the pipeline.
        """
        ...


# ---------------------------------------------------------------------------
# WebhookPipeline
# ---------------------------------------------------------------------------


class WebhookPipeline:
    """Sequential webhook processing pipeline.

    Runs the payload through stages in strict order:
    dedup → loop_guard → dispatcher.

    Any stage returning an action other than PASS stops the pipeline.
    Every stage result is audited regardless of outcome.
    """

    def __init__(self, stages: list[PipelineStage]) -> None:
        """Initialize the pipeline with ordered stages.

        Parameters
        ----------
        stages:
            List of pipeline stages to execute in order.
            Typically: [EventDedup, LoopGuard, WebhookDispatcher]
        """
        self._stages = stages

    @property
    def stages(self) -> list[PipelineStage]:
        """Return the ordered list of pipeline stages."""
        return list(self._stages)

    async def process(self, payload: WebhookPayload) -> PipelineResult:
        """Run payload through all stages sequentially.

        Each stage can either PASS (continue to next) or return a
        terminal action (DROP, SIGNALED, WORKFLOW_STARTED, etc.).
        All stage results are audited.

        Parameters
        ----------
        payload:
            The normalized webhook payload to process.

        Returns
        -------
        PipelineResult
            The final pipeline result with all stage outcomes.
        """
        stage_results: list[tuple[str, StageResult]] = []
        trace_id = payload.trace_id

        for stage in self._stages:
            start_time = time.monotonic()
            try:
                result = await stage.check(payload)
            except Exception as exc:
                # Stage raised an unexpected error — log and treat as pass
                # to maintain at-least-once semantics
                _logger.error(
                    "pipeline_stage_error",
                    stage=stage.name,
                    issue_key=payload.issue_key,
                    event_type=payload.event_type,
                    error=str(exc),
                    error_type=type(exc).__name__,
                )
                result = StageResult(
                    action=StageAction.PASS,
                    reason=f"stage_error: {type(exc).__name__}",
                )

            elapsed_ms = int((time.monotonic() - start_time) * 1000)

            # Propagate trace_id from stage result if generated
            if result.trace_id:
                trace_id = result.trace_id

            stage_results.append((stage.name, result))

            # Audit every stage result
            _audit_stage_result(
                stage_name=stage.name,
                result=result,
                payload=payload,
                elapsed_ms=elapsed_ms,
            )

            # If the stage did not pass, stop the pipeline
            if result.action != StageAction.PASS:
                return PipelineResult(
                    final_action=result.action,
                    stage_results=stage_results,
                    dropped_at=stage.name,
                    trace_id=trace_id,
                )

        # All stages passed — this shouldn't normally happen because
        # the dispatcher stage should return a terminal action
        # (workflow_started, signaled, etc.)
        final_action = (
            stage_results[-1][1].action if stage_results else StageAction.PASS
        )
        return PipelineResult(
            final_action=final_action,
            stage_results=stage_results,
            dropped_at=None,
            trace_id=trace_id,
        )


# ---------------------------------------------------------------------------
# Audit helper
# ---------------------------------------------------------------------------


def _audit_stage_result(
    *,
    stage_name: str,
    result: StageResult,
    payload: WebhookPayload,
    elapsed_ms: int,
) -> None:
    """Emit a structured audit log entry for a pipeline stage result."""
    log_fields: dict[str, Any] = {
        "stage": stage_name,
        "action": result.action.value,
        "issue_key": payload.issue_key,
        "event_type": payload.event_type,
        "elapsed_ms": elapsed_ms,
    }
    if result.reason:
        log_fields["reason"] = result.reason
    if result.trace_id:
        log_fields["trace_id"] = result.trace_id
    if result.metadata:
        log_fields["metadata"] = result.metadata
    if payload.actor_account_id:
        log_fields["actor_account_id"] = payload.actor_account_id

    _logger.info("pipeline_stage_result", **log_fields)


# ---------------------------------------------------------------------------
# Payload extraction helpers
# ---------------------------------------------------------------------------


def extract_webhook_payload(
    raw_payload: dict[str, Any],
    headers: dict[str, str],
) -> WebhookPayload:
    """Extract a normalized WebhookPayload from raw Jira webhook data.

    Parameters
    ----------
    raw_payload:
        The decoded JSON body of the webhook request.
    headers:
        Relevant HTTP headers (lowercased keys).

    Returns
    -------
    WebhookPayload
        Normalized payload ready for pipeline processing.
    """
    # Extract event_id from header or derive from payload
    event_id = headers.get("x-atlassian-webhook-identifier")
    if not event_id:
        event_id = _derive_event_id(raw_payload)

    # Extract event type
    event_type = raw_payload.get("webhookEvent", "")

    # Extract issue key
    issue = raw_payload.get("issue", {})
    issue_key = issue.get("key", "") if isinstance(issue, dict) else ""

    # Extract actor account ID
    actor_account_id: str | None = None
    user = raw_payload.get("user")
    if isinstance(user, dict):
        actor_account_id = user.get("accountId")

    # Extract assignee account ID
    assignee_account_id: str | None = None
    reporter_account_id: str | None = None
    if isinstance(issue, dict):
        fields = issue.get("fields", {})
        if isinstance(fields, dict):
            assignee = fields.get("assignee")
            if isinstance(assignee, dict):
                assignee_account_id = assignee.get("accountId")
            reporter = fields.get("reporter")
            if isinstance(reporter, dict):
                reporter_account_id = reporter.get("accountId")

    # Extract comment body
    comment_body: str | None = None
    comment = raw_payload.get("comment")
    if isinstance(comment, dict):
        comment_body = comment.get("body")

    # Extract trace_id from headers (for retry scenarios)
    trace_id = headers.get("x-trace-id")

    return WebhookPayload(
        event_id=event_id,
        event_type=event_type,
        issue_key=issue_key,
        actor_account_id=actor_account_id,
        assignee_account_id=assignee_account_id,
        reporter_account_id=reporter_account_id,
        comment_body=comment_body,
        trace_id=trace_id,
        raw_payload=raw_payload,
        headers=headers,
    )


def _derive_event_id(payload: dict[str, Any]) -> str:
    """Derive a deterministic event_id from payload fields.

    Uses SHA-256 hash of webhookEvent + timestamp + issue.id to create
    a unique identifier when the X-Atlassian-Webhook-Identifier header
    is not available.
    """
    event_type = payload.get("webhookEvent", "")
    timestamp = str(payload.get("timestamp", ""))
    issue = payload.get("issue", {})
    issue_id = str(issue.get("id", "")) if isinstance(issue, dict) else ""

    composite = f"{event_type}:{timestamp}:{issue_id}"
    return hashlib.sha256(composite.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Stage Adapters — bridge component-specific types to PipelineStage Protocol
# ---------------------------------------------------------------------------
#
# The three pipeline components (``EventDedup``, ``LoopGuard``,
# ``WebhookDispatcher``) each ship their own payload + result shapes
# from tasks 1.2 / 1.3 / 1.4. The pipeline orchestrator above operates
# on the canonical :class:`WebhookPayload` and :class:`StageResult`
# defined here. Rather than break those component contracts (which
# already have unit-test coverage at ``test_dedup``, ``test_loop_guard``
# and ``test_webhooks_dispatcher``), each adapter translates the
# pipeline payload into the component's input, runs the component, and
# maps the component result back to a :class:`StageResult`.
#
# The translation is intentionally lossless — the raw payload bytes,
# headers, and metadata fields all flow through so audit rows emitted
# from inside the components carry the same identifiers the pipeline
# attached at extraction time.


class DedupStage:
    """PipelineStage adapter for :class:`webhooks.dedup.EventDedup`."""

    def __init__(self, dedup: Any) -> None:
        self._dedup = dedup

    @property
    def name(self) -> str:
        return "dedup"

    async def check(self, payload: WebhookPayload) -> StageResult:
        # ``EventDedup`` consumes the dedup-module's local
        # ``WebhookPayload`` (raw_body + headers + body dict). Build a
        # compatible shape on the fly so the dedup component's
        # contract stays unchanged.
        from .dedup import WebhookPayload as DedupPayload

        # Reconstruct headers into the dedup payload's lowercased map.
        # We always have ``payload.headers`` (lowercased) thanks to
        # :func:`extract_webhook_payload`. Raw bytes are not strictly
        # required because the dedup ID is derived from header or
        # body fields — we pass an empty bytes literal to satisfy the
        # dataclass.
        dedup_payload = DedupPayload(
            headers=dict(payload.headers),
            body=dict(payload.raw_payload),
            raw_body=b"",
        )

        result = await self._dedup.check(dedup_payload)

        if result.action == "drop":
            return StageResult(
                action=StageAction.DROP,
                reason=result.reason or "duplicate",
            )
        return StageResult(action=StageAction.PASS)


class LoopGuardStage:
    """PipelineStage adapter for :class:`webhooks.loop_guard.LoopGuard`."""

    def __init__(self, loop_guard: Any) -> None:
        self._loop_guard = loop_guard

    @property
    def name(self) -> str:
        return "loop_guard"

    async def check(self, payload: WebhookPayload) -> StageResult:
        # ``LoopGuard`` consumes the loop_guard module's local
        # ``WebhookPayload`` shape. Map the canonical pipeline payload
        # onto it so the guard sees actor/issue/event/comment in the
        # exact field names it expects.
        from .loop_guard import WebhookPayload as LoopGuardPayload

        lg_payload = LoopGuardPayload(
            actor_account_id=payload.actor_account_id,
            issue_key=payload.issue_key,
            event_type=payload.event_type,
            comment_body=payload.comment_body,
            assignee_account_id=payload.assignee_account_id,
            reporter_account_id=payload.reporter_account_id,
            dept_id=None,
            trace_id=payload.trace_id,
        )

        result = await self._loop_guard.check(lg_payload)

        if result.action == "drop":
            return StageResult(
                action=StageAction.DROP,
                reason=result.reason or "loop_guard",
            )
        return StageResult(action=StageAction.PASS)


class DispatcherStage:
    """PipelineStage adapter for :class:`webhooks.dispatcher.WebhookDispatcher`."""

    def __init__(self, dispatcher: Any) -> None:
        self._dispatcher = dispatcher

    @property
    def name(self) -> str:
        return "dispatcher"

    async def check(self, payload: WebhookPayload) -> StageResult:
        # ``WebhookDispatcher`` consumes the loop_guard module's
        # ``WebhookPayload`` (the dispatcher imports it from
        # :mod:`webhooks.loop_guard` to avoid duplication). Build the
        # same shape so the dispatcher's contract stays unchanged.
        from .loop_guard import WebhookPayload as DispatcherPayload

        disp_payload = DispatcherPayload(
            actor_account_id=payload.actor_account_id,
            issue_key=payload.issue_key,
            event_type=payload.event_type,
            comment_body=payload.comment_body,
            assignee_account_id=payload.assignee_account_id,
            reporter_account_id=payload.reporter_account_id,
            dept_id=None,
            trace_id=payload.trace_id,
        )

        result = await self._dispatcher.dispatch(disp_payload)

        # Map the dispatcher's string action onto the pipeline's
        # ``StageAction`` enum. ``DispatchResult`` uses string
        # discriminators (``"drop"``, ``"signaled"``, ``"workflow_started"``,
        # ``"iteration_started"``, ``"budget_exceeded"``,
        # ``"budget_configuration_error"``) which align byte-for-byte
        # with the enum values.
        action_map = {
            "drop": StageAction.DROP,
            "signaled": StageAction.SIGNALED,
            "workflow_started": StageAction.WORKFLOW_STARTED,
            "iteration_started": StageAction.ITERATION_STARTED,
            "approval_forwarded": StageAction.APPROVAL_FORWARDED,
            "budget_exceeded": StageAction.BUDGET_EXCEEDED,
            "budget_configuration_error": StageAction.BUDGET_CONFIGURATION_ERROR,
            "pass": StageAction.PASS,
        }
        action = action_map.get(result.action, StageAction.DROP)

        metadata: dict[str, Any] = {}
        if result.dept_id:
            metadata["dept_id"] = result.dept_id
        # Propagate the HTTP status code + body when the dispatcher
        # produced a custom response shape (e.g. budget_exceeded → 429
        # with a ``deny_response_body`` payload). The orchestrator
        # picks these up to render the final HTTP response.
        if getattr(result, "status_code", None) is not None:
            metadata["status_code"] = result.status_code
        if getattr(result, "body", None) is not None:
            metadata["body"] = result.body

        return StageResult(
            action=action,
            reason=result.reason,
            trace_id=result.trace_id,
            metadata=metadata,
        )


def build_webhook_pipeline(
    *,
    db: Any,
    temporal: Any,
    audit_logger: Any | None = None,
    vault: Any | None = None,
    jira_commenter: Any | None = None,
    admin_notifier: Any | None = None,
    budget_policy: Any | None = None,
) -> WebhookPipeline:
    """Construct the canonical webhook pipeline (dedup → loop_guard → dispatcher).

    Production wiring builds this once during the FastAPI lifespan
    startup and stashes it on ``app.state.webhook_pipeline``. Tests
    can call the same factory with hand-rolled fakes, or inject a
    pre-built :class:`WebhookPipeline` directly.

    Parameters
    ----------
    db:
        Async database pool (asyncpg-compatible).  Required.
    temporal:
        Temporal client used by the dispatcher to start workflows
        and send signals.  Required.
    audit_logger:
        Optional :class:`audit_logger.AuditLogger` used by the
        loop guard and dispatcher.  Defaults to ``None`` (structured
        log fallback).
    vault:
        Optional vault client used by the dispatcher for cache-miss
        credential lookups.
    jira_commenter:
        Optional Jira commenter used by the dispatcher to post
        rejection notes when the per-dept concurrency cap fires
        or when the budget enforcement runtime guard denies a workflow
        start.
    admin_notifier:
        Optional admin notifier used by the loop guard for storm
        alerts.
    budget_policy:
        Optional :class:`automation_service.budget.policy.BudgetCapPolicy`.
        When wired, the dispatcher invokes ``check_budget`` before
        any workflow start and short-circuits with HTTP 429 +
        ``deny_response_body`` on cap breach. Audit + Jira comment
        side effects are written by the policy itself.

    Returns
    -------
    WebhookPipeline
        The orchestrator wrapping the three component stages.
    """
    from .dedup import EventDedup
    from .dispatcher import WebhookDispatcher
    from .loop_guard import LoopGuard

    dedup = EventDedup(db=db)
    loop_guard = LoopGuard(
        db=db,
        audit_logger=audit_logger,
        admin_notifier=admin_notifier,
    )
    dispatcher = WebhookDispatcher(
        db=db,
        temporal=temporal,
        audit_logger=audit_logger,
        vault=vault,
        jira_commenter=jira_commenter,
        budget_policy=budget_policy,
    )

    return WebhookPipeline(
        stages=[
            DedupStage(dedup),
            LoopGuardStage(loop_guard),
            DispatcherStage(dispatcher),
        ]
    )


# ---------------------------------------------------------------------------
# FastAPI Router
# ---------------------------------------------------------------------------

router = APIRouter(tags=["webhooks-pipeline"])


@router.post("/jira/pipeline")
async def post_jira_webhook_pipeline(request: Request) -> JSONResponse:
    """Handle ``POST /webhooks/jira/pipeline`` via the pipeline orchestrator.

    This endpoint processes Jira webhooks through the sequential pipeline:
    dedup → loop_guard → dispatcher.

    The pipeline instance is expected on ``request.app.state.webhook_pipeline``
    (a :class:`WebhookPipeline`). If not wired, returns 503.

    Returns 200 for all successfully processed webhooks (whether passed,
    dropped, or dispatched) — Atlassian expects 200 to acknowledge receipt.
    """
    # Retrieve the pipeline from app state
    pipeline: WebhookPipeline | None = getattr(
        request.app.state, "webhook_pipeline", None
    )
    if pipeline is None:
        _logger.error("webhook_pipeline_not_configured")
        return JSONResponse(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            content={"status": "pipeline_not_configured"},
        )

    # Read raw body
    raw_body: bytes = await request.body()

    # Parse JSON
    try:
        import json

        decoded = json.loads(raw_body or b"{}")
    except (ValueError, TypeError):
        _logger.warning("webhook_bad_json", source="jira_pipeline")
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"status": "bad_request", "reason": "invalid_json"},
        )

    if not isinstance(decoded, dict):
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"status": "bad_request", "reason": "payload_not_object"},
        )

    # Extract headers (lowercase keys)
    headers: dict[str, str] = {
        k.lower(): v
        for k, v in request.headers.items()
    }

    # Build normalized payload
    payload = extract_webhook_payload(decoded, headers)

    # Validate minimum required fields
    if not payload.event_type:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"status": "bad_request", "reason": "missing_event_type"},
        )
    if not payload.issue_key:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"status": "bad_request", "reason": "missing_issue_key"},
        )

    # Run through pipeline
    result = await pipeline.process(payload)

    # Build response based on pipeline result
    response_content: dict[str, Any] = {
        "status": result.final_action.value,
    }
    if result.dropped_at:
        response_content["dropped_at"] = result.dropped_at
    if result.trace_id:
        response_content["trace_id"] = result.trace_id

    # Extract additional metadata from the last stage result
    last_reason: str | None = None
    if result.stage_results:
        last_stage_name, last_result = result.stage_results[-1]
        if last_result.reason:
            response_content["reason"] = last_result.reason
            last_reason = last_result.reason
        if last_result.metadata:
            response_content.update(last_result.metadata)

    # Audit the full pipeline outcome
    _logger.info(
        "pipeline_completed",
        issue_key=payload.issue_key,
        event_type=payload.event_type,
        final_action=result.final_action.value,
        dropped_at=result.dropped_at,
        trace_id=result.trace_id,
        stages_executed=len(result.stage_results),
    )

    # HTTP status mapping:
    # - 429 when the dispatcher rejected on the concurrency cap
    #   (DispatchResult.reason="concurrency_limit_exceeded" surfaces
    #   as HTTP 429 at the FastAPI layer).
    # - 429 + deny_response_body when the dispatcher rejected on the
    #   budget enforcement runtime guard (BUDGET_EXCEEDED action).
    # - 422 + configuration_error_response when the dispatcher
    #   rejected on an undefined dept_id in budget_caps configuration.
    # - 200 for everything else (Atlassian expects 200 to acknowledge
    #   receipt regardless of dedup/loop-guard/dispatch outcome).
    http_status = status.HTTP_200_OK
    custom_body: dict[str, Any] | None = None
    if result.stage_results:
        _, last_stage_result = result.stage_results[-1]
        meta = last_stage_result.metadata or {}
        meta_status = meta.get("status_code")
        meta_body = meta.get("body")
        if isinstance(meta_status, int):
            http_status = meta_status
        if isinstance(meta_body, dict):
            custom_body = meta_body

    if last_reason == "concurrency_limit_exceeded":
        http_status = status.HTTP_429_TOO_MANY_REQUESTS

    if custom_body is not None:
        # The dispatcher produced an authoritative body (e.g. the
        # ``deny_response_body`` 429 payload). Honour it verbatim
        # rather than overlaying the generic pipeline shape.
        return JSONResponse(
            status_code=http_status,
            content=custom_body,
        )

    return JSONResponse(
        status_code=http_status,
        content=response_content,
    )
