#!/usr/bin/env python3
"""
E2E Suite Orchestrator - runs the full test suite and generates reports.

Executes all E2E tests (test_01 through test_36) in order via pytest,
collects results, invokes ReportGenerator to produce E2E_REPORT.md,
and invokes EvidenceCollector.generate_index() for INDEX.md.

Usage:
    python run_suite.py              # Run full suite
    python run_suite.py --dry-run    # Show what would be executed
    python run_suite.py --tests 1-8  # Run subset (test_01 through test_08)

Requirements: R29.6, R30.1, R30.6
"""

import argparse
import sys
import time
from pathlib import Path

# Ensure the e2e directory is importable
E2E_DIR = Path(__file__).resolve().parent
WORKSPACE_ROOT = E2E_DIR.parent.parent.parent

sys.path.insert(0, str(E2E_DIR))


def discover_test_files(test_range: str | None = None) -> list[Path]:
    """Discover test files in order (test_01 through test_36).

    Args:
        test_range: Optional range string like "1-8" or "5-15".
                    If None, all test files are included.

    Returns:
        Sorted list of test file paths.
    """
    all_tests = sorted(E2E_DIR.glob("test_*.py"))

    if test_range is None:
        return all_tests

    # Parse range like "1-8" or "5-15"
    parts = test_range.split("-")
    if len(parts) == 2:
        start, end = int(parts[0]), int(parts[1])
    elif len(parts) == 1:
        start = end = int(parts[0])
    else:
        print(f"Invalid range format: {test_range}. Use N-M (e.g., 1-8)")
        return all_tests

    filtered = []
    for test_file in all_tests:
        # Extract number from filename like test_01_preflight.py -> 1
        name = test_file.stem  # test_01_preflight
        parts_name = name.split("_")
        if len(parts_name) >= 2:
            try:
                num = int(parts_name[1])
                if start <= num <= end:
                    filtered.append(test_file)
            except ValueError:
                continue

    return filtered


def run_tests(test_files: list[Path], verbose: bool = True) -> int:
    """Execute tests via pytest programmatic API.

    Args:
        test_files: List of test file paths to execute.
        verbose: Whether to enable verbose output.

    Returns:
        pytest exit code (0 = all passed, 1 = some failed, etc.)
    """
    import pytest

    args = [
        str(f) for f in test_files
    ]

    # Add pytest options
    if verbose:
        args.append("-v")

    # Ensure sequential ordering (by filename)
    args.append("-p")
    args.append("no:randomly")

    # Show short traceback for failures
    args.append("--tb=short")

    # Generate JUnit XML for machine-readable results
    junit_path = E2E_DIR / "results.xml"
    args.extend(["--junitxml", str(junit_path)])

    exit_code = pytest.main(args)
    return exit_code


def parse_junit_results(xml_path: Path) -> dict:
    """Parse JUnit XML results to extract pass/fail counts.

    Args:
        xml_path: Path to the JUnit XML file generated by pytest.

    Returns:
        Dict with keys: total, passed, failed, errors, skipped.
    """
    import xml.etree.ElementTree as ET

    results = {"total": 0, "passed": 0, "failed": 0, "errors": 0, "skipped": 0}

    if not xml_path.exists():
        return results

    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()

        # JUnit XML has <testsuite> with attributes
        for testsuite in root.iter("testsuite"):
            results["total"] += int(testsuite.get("tests", 0))
            results["failed"] += int(testsuite.get("failures", 0))
            results["errors"] += int(testsuite.get("errors", 0))
            results["skipped"] += int(testsuite.get("skipped", 0))

        results["passed"] = (
            results["total"] - results["failed"] - results["errors"] - results["skipped"]
        )
    except (ET.ParseError, FileNotFoundError, ValueError) as exc:
        print(f"Warning: Could not parse JUnit XML: {exc}")

    return results


def generate_report() -> Path | None:
    """Invoke ReportGenerator to produce E2E_REPORT.md.

    Returns:
        Path to the generated report, or None if generation failed.
    """
    try:
        from report_generator import ReportGenerator

        generator = ReportGenerator(workspace_root=WORKSPACE_ROOT)

        # Try to load results from evidence files
        results = generator.load_results_from_evidence()

        report_path = generator.generate(results)
        return report_path
    except Exception as exc:
        print(f"Warning: Report generation failed: {exc}")
        return None


def generate_evidence_index() -> Path | None:
    """Invoke EvidenceCollector.generate_index() for INDEX.md.

    Returns:
        Path to the generated INDEX.md, or None if generation failed.
    """
    try:
        from evidence_collector import EvidenceCollector

        evidence_dir = WORKSPACE_ROOT / "e2e-evidence"
        collector = EvidenceCollector(base_dir=evidence_dir)
        index_path = collector.generate_index()
        return index_path
    except Exception as exc:
        print(f"Warning: Evidence index generation failed: {exc}")
        return None


def print_summary(results: dict, duration: float, report_path: Path | None, index_path: Path | None):
    """Print a human-readable summary to stdout.

    Args:
        results: Dict with pass/fail counts from parse_junit_results.
        duration: Total suite duration in seconds.
        report_path: Path to E2E_REPORT.md or None.
        index_path: Path to INDEX.md or None.
    """
    total = results["total"]
    passed = results["passed"]
    failed = results["failed"]
    errors = results["errors"]
    skipped = results["skipped"]

    print("\n" + "=" * 60)
    print("  E2E SUITE EXECUTION SUMMARY")
    print("=" * 60)
    print(f"\n  E2E Suite: {passed}/{total} passed, {failed} failed")

    if errors > 0:
        print(f"  Errors: {errors}")
    if skipped > 0:
        print(f"  Skipped: {skipped}")

    print(f"  Duration: {duration:.1f}s ({duration / 60:.1f} min)")

    # Status indicator
    if failed == 0 and errors == 0:
        print("\n  🟢 ALL TESTS PASSED")
    else:
        print(f"\n  🔴 {failed + errors} ISSUE(S) FOUND")

    # Report artifacts
    print("\n  Artifacts:")
    if report_path and report_path.exists():
        print(f"    📄 Report: {report_path.relative_to(WORKSPACE_ROOT)}")
    else:
        print("    📄 Report: (not generated)")

    if index_path and index_path.exists():
        print(f"    📋 Evidence Index: {index_path.relative_to(WORKSPACE_ROOT)}")
    else:
        print("    📋 Evidence Index: (not generated)")

    print("\n" + "=" * 60)


def main():
    """Main entry point for the E2E suite orchestrator."""
    parser = argparse.ArgumentParser(
        description="Run the full E2E test suite and generate reports."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be executed without running tests.",
    )
    parser.add_argument(
        "--tests",
        type=str,
        default=None,
        help="Test range to run (e.g., '1-8' for test_01 through test_08).",
    )
    parser.add_argument(
        "--no-report",
        action="store_true",
        help="Skip report generation after tests.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Reduce pytest output verbosity.",
    )

    args = parser.parse_args()

    # Discover test files
    test_files = discover_test_files(args.tests)

    if not test_files:
        print("No test files found matching the criteria.")
        sys.exit(1)

    print(f"E2E Suite: Found {len(test_files)} test file(s)")

    if args.dry_run:
        print("\nTest files to execute (dry-run):")
        for f in test_files:
            print(f"  - {f.name}")
        print("\nUse without --dry-run to execute.")
        sys.exit(0)

    # Run tests
    print(f"\nExecuting {len(test_files)} test file(s)...")
    start_time = time.time()

    exit_code = run_tests(test_files, verbose=not args.quiet)

    duration = time.time() - start_time

    # Parse results from JUnit XML
    junit_path = E2E_DIR / "results.xml"
    results = parse_junit_results(junit_path)

    # Generate report and evidence index
    report_path = None
    index_path = None

    if not args.no_report:
        print("\nGenerating E2E_REPORT.md...")
        report_path = generate_report()

        print("Generating evidence INDEX.md...")
        index_path = generate_evidence_index()

    # Print summary
    print_summary(results, duration, report_path, index_path)

    # Exit with pytest's exit code
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
