"""Behavioral tests for Sensitive_Env_Key matcher TS ↔ Python parity.

For any uppercase environment-variable-style key drawn from
``[A-Z][A-Z0-9_]{3,40}``, the **Python** matcher
:func:`src.lifecycle.sensitive.is_sensitive_env_key` and the
**TypeScript** matcher :func:`isSensitiveEnvKey` (compiled from
``libs/web-shared/src/sensitive.ts`` to ``libs/web-shared/dist/sensitive.js``)
SHALL agree **bit-for-bit** on whether the key is a Sensitive_Env_Key.

This structural parity guarantee covers the form ``is_sensitive`` flag,
log redaction, and audit ``details_json`` redaction: both halves of the
control plane must converge on the *same* answer for every input or one
side could under-redact.

Strategy
--------
* Keys are generated by ``st.from_regex(r"[A-Z][A-Z0-9_]{3,40}",
  fullmatch=True)``. The fullmatch flag pins the regex
  to ``^…$`` so generated strings never contain newlines or
  characters outside the env-var alphabet - exactly the universe both
  matchers were designed for.

* Each Hypothesis example produces a **batch** of keys. A *single*
  Node invocation evaluates all of them in one shot and returns a
  JSON list of booleans. This keeps the test budget bounded:
  spawning ``node`` per key would multiply 30 examples × ~10 keys ×
  ~50 ms = ≥15 s; one process per example keeps the run well under a
  second on top of Hypothesis's own overhead.

* The Node side imports the compiled ESM module via a ``file://``
  URL and reads the JSON key list from stdin to side-step Windows
  command-line quoting issues.

Skip semantics
--------------
* ``shutil.which("node")`` returns ``None`` → ``pytest.skip("node
  not available")``.

* ``libs/web-shared/dist/sensitive.js`` does not exist → the fixture
  attempts ``npm run build`` (after a one-shot ``npm install`` if
  ``node_modules`` is missing). If either step fails, the test
  ``pytest.skip``s with the failing command and stderr captured for
  debugging.

* Concrete regression anchors run **after** the fixture has
  succeeded, so they share the same skip semantics as the property.

Concrete regression anchors
---------------------------
``test_concrete_regression_anchors`` exercises one example per
documented suffix (``_TOKEN``, ``_KEY``, ``_SECRET``, ``_PASSWORD``,
``_DSN``, ``_CREDENTIAL``) plus the ``_PRIVATE_`` infix and a few
known-negative names. These pin the property surface so a regression
in either matcher fails this file deterministically - independent of
the Hypothesis search order.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

# ``conftest.py`` lives one directory up; pytest auto-loads it but we
# add ``tests/`` to ``sys.path`` defensively so this module also imports
# cleanly under a direct ``python -m pytest tests/property`` invocation
# (mirrors the pattern used by the other property tests in this folder).
_TESTS_DIR = Path(__file__).resolve().parent.parent
if str(_TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(_TESTS_DIR))

# The ``admin-dashboard-api`` package is not pip-installed inside the
# test environment, so we expose its source tree on ``sys.path`` the
# same way the per-service unit tests do. This lets us
# ``import src.lifecycle.sensitive`` directly (mirrors the pattern in
# ``tests/property/test_log_redaction.py`` and ``test_stop_idempotent.py``).
_WORKSPACE_ROOT = Path(__file__).resolve().parents[2]
_SERVICE_ROOT = _WORKSPACE_ROOT / "services" / "admin-dashboard-api"
if str(_SERVICE_ROOT) not in sys.path:
    sys.path.insert(0, str(_SERVICE_ROOT))

from src.lifecycle.sensitive import is_sensitive_env_key  # noqa: E402


# ---------------------------------------------------------------------------
# Web-shared TS twin: build / skip plumbing
# ---------------------------------------------------------------------------


_WEB_SHARED_DIR: Path = _WORKSPACE_ROOT / "libs" / "web-shared"
_DIST_SENSITIVE: Path = _WEB_SHARED_DIR / "dist" / "sensitive.js"
_PACKAGE_JSON: Path = _WEB_SHARED_DIR / "package.json"


def _resolve_node() -> str:
    """Return absolute path to ``node`` or ``pytest.skip``.

    The test skips cleanly when the Node binary is not on ``PATH``
    rather than failing; the parity guarantee is structural and a
    missing toolchain is a CI gap, not a regression.
    """

    node = shutil.which("node")
    if node is None:
        pytest.skip("node not available")
    return node


def _resolve_npm() -> str | None:
    """Return absolute path to ``npm``, or ``None`` if missing.

    ``None`` is a soft-fail: the build step will then ``pytest.skip``
    with a precise reason rather than crashing on ``FileNotFoundError``.
    """

    return shutil.which("npm")


def _run(argv: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    """Run ``argv`` with text-mode stdout/stderr capture and a 5-min cap.

    The 5-minute cap exists so a hung ``npm install`` cannot stall the
    full property suite; in practice the install completes in seconds
    when the lockfile is present.
    """

    return subprocess.run(  # noqa: S603 - argv is fully constructed in-process.
        argv,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=300,
    )


def _ensure_dist_sensitive_built() -> Path:
    """Return the path to ``dist/sensitive.js``, building it if needed.

    Skip semantics
    --------------
    * If ``package.json`` is missing the ``build`` script entry → skip
      with a precise message.
    * If ``node_modules`` is missing and ``npm`` is not on ``PATH`` →
      skip (no way to install ``typescript`` to drive ``tsc``).
    * If ``npm install`` or ``npm run build`` fails → skip with the
      command's stderr so a developer can reproduce the failure
      locally.

    The function is idempotent: once ``dist/sensitive.js`` exists it
    short-circuits, so the per-example cost during the property loop
    is zero.
    """

    if _DIST_SENSITIVE.is_file():
        return _DIST_SENSITIVE

    # Validate the build script up front so the skip message is
    # precise.
    try:
        package_meta = json.loads(_PACKAGE_JSON.read_text(encoding="utf-8"))
    except FileNotFoundError:
        pytest.skip(f"libs/web-shared/package.json missing: {_PACKAGE_JSON}")
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive
        pytest.skip(f"libs/web-shared/package.json is not valid JSON: {exc}")
    scripts = package_meta.get("scripts") or {}
    if "build" not in scripts:
        pytest.skip(
            "libs/web-shared/package.json has no 'build' script"
        )

    npm = _resolve_npm()
    if npm is None:
        pytest.skip("npm not available; cannot build libs/web-shared/dist/sensitive.js")

    # Run ``npm install`` only when ``node_modules`` is absent - a
    # populated tree means the lockfile-driven install already
    # happened (developer machine or CI cache).
    if not (_WEB_SHARED_DIR / "node_modules").is_dir():
        install = _run(
            [npm, "install", "--no-audit", "--no-fund", "--silent"],
            cwd=_WEB_SHARED_DIR,
        )
        if install.returncode != 0:
            pytest.skip(
                "npm install failed for libs/web-shared "
                f"(exit={install.returncode}): {install.stderr.strip() or install.stdout.strip()}"
            )

    build = _run([npm, "run", "build", "--silent"], cwd=_WEB_SHARED_DIR)
    if build.returncode != 0:
        pytest.skip(
            "npm run build failed for libs/web-shared "
            f"(exit={build.returncode}): {build.stderr.strip() or build.stdout.strip()}"
        )

    if not _DIST_SENSITIVE.is_file():
        pytest.skip(
            f"npm run build succeeded but {_DIST_SENSITIVE} is still missing; "
            "check tsconfig output paths."
        )
    return _DIST_SENSITIVE


# Inline Node script that imports the compiled ESM module via a
# ``file://`` URL passed as ``argv[1]`` and reads a JSON list of keys
# from stdin. Stdout is a JSON list of booleans, parallel to the input
# list. Routing keys through stdin avoids Windows ``cmd.exe`` quoting
# pitfalls when the alphabet contains ``"`` or ``\\`` (``st.from_regex``
# does not generate these characters with the current strategy, but
# stdin is the more robust contract).
_NODE_PARITY_SCRIPT: str = (
    "(async () => {"
    "  const mod = await import(process.argv[1]);"
    "  let buf = '';"
    "  for await (const chunk of process.stdin) buf += chunk;"
    "  const keys = JSON.parse(buf);"
    "  process.stdout.write("
    "    JSON.stringify(keys.map((k) => mod.isSensitiveEnvKey(k)))"
    "  );"
    "})().catch((err) => { console.error(err && err.stack || String(err)); process.exit(1); });"
)


def _node_evaluate_keys(node: str, dist_path: Path, keys: list[str]) -> list[bool]:
    """Run the inline Node script once and return parity booleans.

    Single-process batching is critical: spawning Node per key would
    dominate the test runtime by an order of magnitude.
    """

    # ``Path.as_uri()`` produces a ``file:///`` URL on every platform
    # (including Windows drive letters), which is exactly what the
    # ESM loader expects.
    file_url = dist_path.resolve().as_uri()
    payload = json.dumps(keys, ensure_ascii=True)

    proc = subprocess.run(  # noqa: S603 - argv is fully constructed in-process.
        [node, "-e", _NODE_PARITY_SCRIPT, file_url],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            "node parity helper failed "
            f"(exit={proc.returncode}): {proc.stderr.strip() or proc.stdout.strip()}"
        )

    try:
        result = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"node parity helper produced non-JSON stdout: {proc.stdout!r}"
        ) from exc

    if not isinstance(result, list) or len(result) != len(keys):
        raise RuntimeError(
            "node parity helper returned a list of unexpected shape: "
            f"len={len(result) if isinstance(result, list) else 'N/A'}, "
            f"expected={len(keys)}, payload={result!r}"
        )
    if not all(isinstance(b, bool) for b in result):
        raise RuntimeError(
            f"node parity helper returned non-bool entries: {result!r}"
        )
    return result


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def node_binary() -> str:
    """Resolved ``node`` path; skips the module if Node is absent."""

    return _resolve_node()


@pytest.fixture(scope="module")
def dist_sensitive_path() -> Path:
    """Path to the compiled TS twin; builds (or skips) on first use."""

    return _ensure_dist_sensitive_built()


# ---------------------------------------------------------------------------
# TS ↔ Python parity over a random key universe
# ---------------------------------------------------------------------------


# ``[A-Z][A-Z0-9_]{3,40}`` - uppercase env-var alphabet, length 4..41.
# ``fullmatch=True`` pins the regex to ``^…$`` so the generator cannot
# emit characters outside the documented universe (no newlines, no
# lowercase, no quotes); both matchers were specified against this
# alphabet.
_KEY_STRATEGY: st.SearchStrategy[str] = st.from_regex(
    r"[A-Z][A-Z0-9_]{3,40}", fullmatch=True
)


@given(
    keys=st.lists(_KEY_STRATEGY, min_size=1, max_size=12),
)
@settings(
    deadline=None,
    max_examples=30,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
def test_python_and_typescript_matchers_agree(
    keys: list[str],
    node_binary: str,
    dist_sensitive_path: Path,
) -> None:
    """Python and TypeScript matchers agree on every key.

    The two halves are evaluated against the **same** input batch,
    then compared element-wise. Any divergence - in either direction
    (Python true / TS false, or vice versa) - fails the property and
    surfaces the offending key in Hypothesis's counterexample output.
    """

    py_results: list[bool] = [is_sensitive_env_key(k) for k in keys]
    ts_results: list[bool] = _node_evaluate_keys(
        node_binary, dist_sensitive_path, keys
    )

    assert ts_results == py_results, (
        "TS↔Python Sensitive_Env_Key parity broken. "
        f"keys={keys!r}, python={py_results!r}, typescript={ts_results!r}, "
        f"divergences={[ (k, py, ts) for k, py, ts in zip(keys, py_results, ts_results) if py != ts ]!r}"
    )


# ---------------------------------------------------------------------------
# Concrete regression anchors (one per documented suffix + infix +
# negatives). These pin the property surface so a regression in either
# matcher fails this file deterministically.
# ---------------------------------------------------------------------------


# ``(key, expected_sensitive)`` - covers each documented suffix at least
# once plus the ``_PRIVATE_`` infix and three known-negatives
# that exercise the "no leading underscore" boundary (``TOKEN`` etc.)
# referenced in the docstrings of both matcher modules.
_REGRESSION_CASES: tuple[tuple[str, bool], ...] = (
    # Suffix anchors
    ("VAULT_TOKEN", True),
    ("API_KEY", True),
    ("JWT_SECRET", True),
    ("DB_PASSWORD", True),
    ("POSTGRES_DSN", True),
    ("OAUTH_CREDENTIAL", True),
    # Infix anchor
    ("DB_PRIVATE_HOST", True),
    ("APP_PRIVATE_KEY_PATH", True),  # infix wins even when no suffix matches
    # Negatives - bare names that match the glob ``KEY`` etc. without
    # the leading underscore are NOT sensitive (mirrors the docstrings
    # in both matcher modules).
    ("TOKEN", False),
    ("KEY", False),
    ("SECRET", False),
    ("LOG_LEVEL", False),
    ("PORT", False),
    ("WORKER_NAME", False),
)


def _format_anchor(case: tuple[str, bool]) -> str:
    """Compact pytest-id renderer for the regression matrix."""

    key, expected = case
    return f"{key}->{ 'T' if expected else 'F' }"


@pytest.mark.parametrize(
    "case",
    _REGRESSION_CASES,
    ids=[_format_anchor(c) for c in _REGRESSION_CASES],
)
def test_concrete_regression_anchors(
    case: tuple[str, bool],
    node_binary: str,
    dist_sensitive_path: Path,
) -> None:
    """Concrete anchors covering every Sensitive_Env_Key pattern shape.

    Each case asserts three things at once:

    1. The Python matcher returns ``expected``.
    2. The TS matcher returns ``expected``.
    3. The two matchers agree (redundant given 1 + 2 but kept as an
       explicit assertion so the failure message names the parity
       contract directly).
    """

    key, expected = case

    py_result = is_sensitive_env_key(key)
    ts_result = _node_evaluate_keys(node_binary, dist_sensitive_path, [key])[0]

    assert py_result is expected, (
        f"Python matcher disagrees with anchor for {key!r}: "
        f"python={py_result!r}, expected={expected!r}"
    )
    assert ts_result is expected, (
        f"TypeScript matcher disagrees with anchor for {key!r}: "
        f"typescript={ts_result!r}, expected={expected!r}"
    )
    assert py_result == ts_result, (
        f"TS↔Python Sensitive_Env_Key parity broken on anchor {key!r}: "
        f"python={py_result!r}, typescript={ts_result!r}"
    )


def test_keys_strategy_alphabet_is_what_we_documented() -> None:
    """Sanity guard: the regex strategy never emits forbidden chars.

    Both matcher modules document an uppercase, no-newline universe;
    if a future edit relaxes ``_KEY_STRATEGY`` (e.g. allowing
    lowercase) without updating the matchers we want a fast,
    deterministic failure here rather than an obscure counterexample
    from the property test.
    """

    sample_keys: Iterable[str] = (
        # Hand-built representatives that hit each character class
        # the strategy is allowed to emit. If the strategy is ever
        # widened, pick samples that prove the new alphabet
        # explicitly rather than relying on this guard.
        "ABCD",  # 4 chars (lower bound)
        "Z9_3",  # mixes uppercase, digit, underscore
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789ABCD",  # 41 chars (upper bound)
    )
    for k in sample_keys:
        assert k.isascii(), f"alphabet guard: {k!r} is not ASCII"
        assert k[0].isupper(), f"alphabet guard: {k!r} does not start uppercase"
        for ch in k:
            assert ch.isupper() or ch.isdigit() or ch == "_", (
                f"alphabet guard: {k!r} contains forbidden char {ch!r}"
            )
        assert 4 <= len(k) <= 41, (
            f"alphabet guard: {k!r} length {len(k)} outside [4, 41]"
        )
