-- 003_audit_log_feature_flag_action.sql
-- Feature-flag start gate audit action.
--
-- Widens the ``shared.audit_log.action`` CHECK constraint to include
-- ``service_start_blocked_feature_flag`` so the lifecycle handler can
-- record a Step 1.5 block when a manifest ``feature_flag_dependency``
-- is disabled.
--
-- The original constraint was defined by ``50_shared.sql`` as::
--
--     action TEXT NOT NULL CHECK (action IN (
--         'start', 'stop', 'restart', 'run_tests', 'health_streak_alert'
--     ))
--
-- Idempotent — drops the previous constraint name (auto-generated by
-- Postgres in the inline form ``CHECK (...)``) only when present, then
-- adds the new named constraint. Re-running on an already-migrated DB
-- is a no-op (the lookup just finds the new constraint already in place).

DO $$
DECLARE
    old_constraint_name TEXT;
BEGIN
    -- Locate the original CHECK constraint on shared.audit_log.action.
    -- The constraint name is auto-generated (e.g. "audit_log_action_check")
    -- so we resolve it by inspecting the constraint definitions; we drop
    -- whichever check constraint references the ``action`` column AND
    -- restricts to the original five values.
    SELECT conname
      INTO old_constraint_name
      FROM pg_constraint
      JOIN pg_class ON pg_class.oid = pg_constraint.conrelid
      JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
     WHERE pg_namespace.nspname = 'shared'
       AND pg_class.relname = 'audit_log'
       AND pg_constraint.contype = 'c'
       AND pg_get_constraintdef(pg_constraint.oid) LIKE '%action%'
       AND pg_get_constraintdef(pg_constraint.oid) NOT LIKE '%service_start_blocked_feature_flag%'
     LIMIT 1;

    IF old_constraint_name IS NOT NULL THEN
        EXECUTE format(
            'ALTER TABLE shared.audit_log DROP CONSTRAINT %I',
            old_constraint_name
        );
    END IF;
END $$;

-- Add the widened constraint with a stable name so subsequent migrations
-- can locate it without grovelling through pg_constraint again.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
          JOIN pg_class ON pg_class.oid = pg_constraint.conrelid
          JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
         WHERE pg_namespace.nspname = 'shared'
           AND pg_class.relname = 'audit_log'
           AND pg_constraint.conname = 'audit_log_action_check_v2'
    ) THEN
        ALTER TABLE shared.audit_log
            ADD CONSTRAINT audit_log_action_check_v2
            CHECK (action IN (
                'start',
                'stop',
                'restart',
                'run_tests',
                'health_streak_alert',
                'service_start_blocked_feature_flag'
            ));
    END IF;
END $$;
